/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_appsync_graphqlEndpoint": "https://6uayj7gbjfgl5ge6yd4ykwxwla.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mm2yhe4xwbeb7h3pvdntjhfozi",
    "aws_cognito_identity_pool_id": "ap-northeast-1:41f7ca0c-8c2e-458f-9731-d5e5112fa81e",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_fOjcEzyf2",
    "aws_user_pools_web_client_id": "6tq76acat15vbvl98nheiufh38",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplifyshophelperv2caaf9c40b76f4ca6927f197b154a235056-main",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
